# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-07 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_auto_20180306_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltimetable',
            name='advisors',
            field=models.ManyToManyField(related_name='Advisors', to='student.Student'),
        ),
    ]
