# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-29 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_auto_20180329_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltimetable',
            name='advisors',
            field=models.ManyToManyField(blank=True, null=True, related_name='Advisors', to='student.Student'),
        ),
    ]
