# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-29 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_auto_20180329_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltimetable',
            name='advisors',
            field=models.ManyToManyField(blank=True, related_name='Advisors', to='student.Student'),
        ),
    ]
