# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-03 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_auto_20180329_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltimetable',
            name='advisors',
            field=models.ManyToManyField(related_name='Advisors', to='student.Student'),
        ),
    ]
