# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-17 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_auto_20180417_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
        migrations.AlterField(
            model_name='personaltimetable',
            name='comments',
            field=models.ManyToManyField(related_name='Comments', to='comments.Comment'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
